export const mockMedicamentos = [
  { id: 1, nome: "Insulina", disponibilidade: "Disponível" },
  { id: 2, nome: "Metformina", disponibilidade: "Disponível" },
  { id: 3, nome: "Paracetamol", disponibilidade: "Disponível" },
  { id: 4, nome: "Ibuprofeno", disponibilidade: "Em falta" },
  { id: 5, nome: "Omeprazol", disponibilidade: "Disponível" },
  { id: 6, nome: "Atorvastatina", disponibilidade: "Disponível" },
  { id: 7, nome: "Losartana", disponibilidade: "Disponível" },
  { id: 8, nome: "AAS (Ácido Acetilsalicílico)", disponibilidade: "Disponível" },
  { id: 9, nome: "Enalapril", disponibilidade: "Em falta" },
  { id: 10, nome: "Amoxicilina", disponibilidade: "Disponível" },
  { id: 11, nome: "Captopril", disponibilidade: "Disponível" },
  { id: 12, nome: "Cefalexina", disponibilidade: "Disponível" },
  { id: 13, nome: "Clonazepam", disponibilidade: "Disponível" },
  { id: 14, nome: "Diazepam", disponibilidade: "Em falta" },
  { id: 15, nome: "Fluoxetina", disponibilidade: "Disponível" },
  { id: 16, nome: "Prednisona", disponibilidade: "Disponível" },
  { id: 17, nome: "Ranitidina", disponibilidade: "Em falta" },
  { id: 18, nome: "Simvastatina", disponibilidade: "Disponível" },
  { id: 19, nome: "Diclofenaco", disponibilidade: "Disponível" },
  { id: 20, nome: "Cetoconazol", disponibilidade: "Disponível" },
  { id: 21, nome: "Albendazol", disponibilidade: "Disponível" },
  { id: 22, nome: "Hidroclorotiazida", disponibilidade: "Em falta" },
  { id: 23, nome: "Carbamazepina", disponibilidade: "Disponível" },
  { id: 24, nome: "Salbutamol", disponibilidade: "Disponível" },
  { id: 25, nome: "Beclometasona", disponibilidade: "Em falta" },
  { id: 26, nome: "Acetilcisteína", disponibilidade: "Disponível" },
  { id: 27, nome: "Cloreto de Potássio", disponibilidade: "Disponível" },
  { id: 28, nome: "Nifedipina", disponibilidade: "Disponível" },
  { id: 29, nome: "Levodopa", disponibilidade: "Disponível" },
  { id: 30, nome: "Cloridrato de Metoclopramida", disponibilidade: "Disponível" },
  { id: 31, nome: "Prometazina", disponibilidade: "Em falta" },
  { id: 32, nome: "Dipirona", disponibilidade: "Disponível" },
  { id: 33, nome: "Clorexidina", disponibilidade: "Disponível" },
  { id: 34, nome: "Fenitoína", disponibilidade: "Disponível" },
  { id: 35, nome: "Carvedilol", disponibilidade: "Disponível" },
  { id: 36, nome: "Cloridrato de Bupropiona", disponibilidade: "Disponível" },
  { id: 37, nome: "Lamotrigina", disponibilidade: "Disponível" },
  { id: 38, nome: "Cloridrato de Ciprofloxacino", disponibilidade: "Disponível" },
  { id: 39, nome: "Cimetidina", disponibilidade: "Disponível" },
  { id: 40, nome: "Mebendazol", disponibilidade: "Disponível" },
  { id: 41, nome: "Ivermectina", disponibilidade: "Disponível" },
  { id: 42, nome: "Azitromicina", disponibilidade: "Disponível" },
  { id: 43, nome: "Propranolol", disponibilidade: "Disponível" },
  { id: 44, nome: "Loratadina", disponibilidade: "Em falta" },
  { id: 45, nome: "Cetirizina", disponibilidade: "Disponível" },
  { id: 46, nome: "Nortriptilina", disponibilidade: "Disponível" },
  { id: 47, nome: "Clonidina", disponibilidade: "Disponível" },
  { id: 48, nome: "Dexametasona", disponibilidade: "Disponível" },
  { id: 49, nome: "Amlodipina", disponibilidade: "Disponível" },
  { id: 50, nome: "Mirtazapina", disponibilidade: "Disponível" },
  { id: 51, nome: "Ciprofloxacino", disponibilidade: "Disponível" },
  { id: 52, nome: "Duloxetina", disponibilidade: "Disponível" },
  { id: 53, nome: "Alprazolam", disponibilidade: "Disponível" },
  { id: 54, nome: "Risperidona", disponibilidade: "Disponível" },
  { id: 55, nome: "Zolpidem", disponibilidade: "Disponível" },
  { id: 56, nome: "Clorazepato", disponibilidade: "Disponível" },
  { id: 57, nome: "Tamsulosina", disponibilidade: "Disponível" },
  { id: 58, nome: "Levetiracetam", disponibilidade: "Disponível" },
  { id: 59, nome: "Flunarizina", disponibilidade: "Disponível" },
  { id: 60, nome: "Salmeterol", disponibilidade: "Disponível" },
  { id: 61, nome: "Montelucaste", disponibilidade: "Disponível" },
  { id: 62, nome: "Bupropiona", disponibilidade: "Disponível" },
  { id: 63, nome: "Verapamil", disponibilidade: "Disponível" },
  { id: 64, nome: "Dipirona sódica", disponibilidade: "Disponível" },
  { id: 65, nome: "Azatioprina", disponibilidade: "Disponível" },
  { id: 66, nome: "Difenidramina", disponibilidade: "Disponível" },
  { id: 67, nome: "Fenobarbital", disponibilidade: "Disponível" },
  { id: 68, nome: "Clindamicina", disponibilidade: "Disponível" },
  { id: 69, nome: "Lansoprazol", disponibilidade: "Disponível" },
  { id: 70, nome: "Loratadina", disponibilidade: "Disponível" },
  { id: 71, nome: "Ranitidina", disponibilidade: "Em falta" },
  { id: 72, nome: "Lisinopril", disponibilidade: "Disponível" },
  { id: 73, nome: "Ceftriaxona", disponibilidade: "Disponível" },
  { id: 74, nome: "Clorpromazina", disponibilidade: "Disponível" },
  { id: 75, nome: "Diazepam", disponibilidade: "Em falta" },
  { id: 76, nome: "Oxcarbazepina", disponibilidade: "Disponível" },
  { id: 77, nome: "Carbamazepina", disponibilidade: "Disponível" },
  { id: 78, nome: "Sertralina", disponibilidade: "Em falta" },
  { id: 79, nome: "Fluoxetina", disponibilidade: "Disponível" },
  { id: 80, nome: "Betametasona", disponibilidade: "Disponível" },
  { id: 81, nome: "Hydrocortisone", disponibilidade: "Disponível" },
  { id: 82, nome: "Fentanil", disponibilidade: "Disponível" },
  { id: 83, nome: "Tramadol", disponibilidade: "Disponível" },
  { id: 84, nome: "Metadona", disponibilidade: "Disponível" },
  { id: 85, nome: "Dihidropiridina", disponibilidade: "Disponível" },
  { id: 86, nome: "Venlafaxina", disponibilidade: "Disponível" },
  { id: 87, nome: "Cloridrato de Sertralina", disponibilidade: "Disponível" },
  { id: 88, nome: "Escitalopram", disponibilidade: "Disponível" },
  { id: 89, nome: "Tianeptina", disponibilidade: "Disponível" },
  { id: 90, nome: "Desvenlafaxina", disponibilidade: "Disponível" },
  { id: 91, nome: "Ácido valproico", disponibilidade: "Disponível" },
  { id: 92, nome: "Piracetam", disponibilidade: "Disponível" },
  { id: 93, nome: "Vitamins A, D, E", disponibilidade: "Disponível" },
  { id: 94, nome: "Ferro", disponibilidade: "Disponível" },
  { id: 95, nome: "Cálcio", disponibilidade: "Disponível" },
  { id: 96, nome: "Loratadina", disponibilidade: "Disponível" },
  { id: 97, nome: "Tiotropium", disponibilidade: "Disponível" },
  { id: 98, nome: "Tadalafil", disponibilidade: "Disponível" },
  { id: 99, nome: "Cefalexina", disponibilidade: "Disponível" },
  { id: 100, nome: "Aspirina", disponibilidade: "Disponível" },
  { id: 101, nome: "Paroxetina", disponibilidade: "Disponível" },
  { id: 102, nome: "Fenilefrina", disponibilidade: "Disponível" },
];
